name: Github Actions Hello World # workflow

on:  # Event
    push:
        branches:
            - master

jobs: # Job
    hello-world:
        runs-on: ubuntu-latest # runner: ubuntu, window, mac-os
        steps:
            - name: echo hello world
              run: echo "Hello World 1"
            - name: working with github actions context
              run: echo "Event Name - ${{ github.event_name }}, Runner - ${{ runner.os }}"

   



