name: Github Actions Hello World # workflow

on:  # Event
    push:
        branches:
            - master

jobs: # Job
    hello-world_1:
        runs-on: ubuntu-latest # runner: ubuntu, window, mac-os
        steps:
            - name: echo hello world
              run: echo "Hello World 1"

    hello-world_2:
        runs-on: ubuntu-latest # runner: ubuntu, window, mac-os
        steps:
            - name: echo hello world
              run: echo "Hello World 2"



