name: unit testing

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: "3.9"
            
            - name: install dependencies
              run:  python -m pip install -–upgrade pip
            
            - name: install dependencies
              run: pip install -r requirements.txt

            - name: run code
              run: pytest